// Generated by CoffeeScript 1.8.0
(function() {
  var GET_COMMANDS, GITHUB_AUTH_HASH, GITHUB_TOKEN_SET, POST_COMMANDS, RESTRICTED_KEYS, app, db, express, favicon, https, repl, start_repl,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  express = require("express");

  repl = require("repl");

  favicon = require("serve-favicon");

  https = require("https");

  db = require("./db").db;

  start_repl = require("./repl").start_repl;

  app = express();

  app.use(favicon("" + __dirname + "/public/favicon.ico"));

  app.use(function(req, res, next) {
    var data;
    data = '';
    req.setEncoding('utf8');
    req.on('data', function(chunk) {
      return data += chunk;
    });
    return req.on('end', function() {
      req.rawBody = data;
      return next();
    });
  });

  GITHUB_TOKEN_SET = "__github_token_set";

  GITHUB_AUTH_HASH = "__github_auth_hash";

  RESTRICTED_KEYS = [GITHUB_TOKEN_SET, GITHUB_AUTH_HASH];

  app.use(function(req, res, next) {
    var key;
    key = req.param("key");
    if (__indexOf.call(RESTRICTED_KEYS, key) >= 0) {
      res.status(403).write("no.");
      return res.send();
    }
    return next();
  });

  app.use(function(req, res, next) {
    var token;
    token = req.query["access_token"] || req.headers["access_token"];
    if (token == null) {
      res.status(403).write("Invalid Access Token");
      return res.send();
    }
    return db.sismember(GITHUB_TOKEN_SET, token, function(err, ismemberres) {
      var cb, options;
      if (err != null) {
        res.status(500).write(err.toString());
        return res.send();
      }
      if (ismemberres === 1) {
        console.log("ISMEMBER");
        next();
      } else {
        options = {
          host: 'api.github.com',
          path: "/user?access_token=" + token,
          headers: {
            "User-Agent": "skyl/hello-express"
          }
        };
        cb = function(gh_response) {
          var str;
          str = '';
          gh_response.on('data', function(chunk) {
            return str += chunk;
          });
          gh_response.on('end', function() {
            return console.log(str);
          });
          if (gh_response.statusCode === 200) {
            console.log("SAVING FROM GITHUB!");
            db.sadd(GITHUB_TOKEN_SET, token);
            db.hset(GITHUB_AUTH_HASH, token, str);
            next();
          } else {
            res.status(403).write("Invalid");
            return res.send();
          }
        };
        return https.request(options, cb).end();
      }
    });
  });

  GET_COMMANDS = ["GET", "LRANGE", "HGET", "HLEN", "HKEYS"];

  app.get('/:command/:key', function(req, res) {
    var args, c, field, key, retrn, _ref;
    c = req.param("command");
    key = req.param("key");
    if (__indexOf.call(RESTRICTED_KEYS, key) >= 0) {
      res.status(403).write("no.");
      return res.send();
    }
    field = req.query.field;
    if (_ref = c.toUpperCase(), __indexOf.call(GET_COMMANDS, _ref) < 0) {
      res.status(400).write("unsupported command");
      return res.send();
    }
    retrn = function(err, dbres) {
      if (!err) {
        if (parseInt(dbres) === dbres) {
          dbres = dbres + "";
        }
        return res.send(dbres);
      } else {
        res.status(500);
        return res.send(err.toString());
      }
    };
    if (field != null) {
      args = [key, field];
    } else {
      args = [key];
    }
    if (req.query.args != null) {
      args.push.apply(args, req.query.args.split(','));
    }
    args.push(retrn);
    return db[c].apply(db, args);
  });

  POST_COMMANDS = ["APPEND", "SET", "LPUSH", "HSET"];

  app.post('/:command/:key', function(req, res) {
    var args, c, field, key, retrn, v, _ref;
    c = req.param("command");
    key = req.param("key");
    field = req.query.field;
    v = req.rawBody;
    if (_ref = c.toUpperCase(), __indexOf.call(POST_COMMANDS, _ref) < 0) {
      res.status(400).write("unsupported command");
      return res.send();
    }
    retrn = function(err, dbres) {
      if (!err) {
        return res.send("true");
      } else {
        res.status(500);
        return res.send(err.toString());
      }
    };
    if (field != null) {
      args = [key, field, v, retrn];
    } else {
      args = [key, v, retrn];
    }
    return db[c].apply(db, args);
  });

  module.exports.app = app;

  module.exports.GITHUB_TOKEN_SET = GITHUB_TOKEN_SET;

  module.exports.GITHUB_AUTH_HASH = GITHUB_AUTH_HASH;

}).call(this);
