// Generated by CoffeeScript 1.8.0
(function() {
  var GITHUB_AUTH_HASH, GITHUB_TOKEN_SET, RESTRICTED_KEYS;

  GITHUB_TOKEN_SET = "__github_token_set";

  GITHUB_AUTH_HASH = "__github_auth_hash";

  RESTRICTED_KEYS = [GITHUB_TOKEN_SET, GITHUB_AUTH_HASH];

  module.exports.GITHUB_TOKEN_SET = GITHUB_TOKEN_SET;

  module.exports.GITHUB_AUTH_HASH = GITHUB_AUTH_HASH;

  module.exports.RESTRICTED_KEYS = RESTRICTED_KEYS;

}).call(this);
