// Generated by CoffeeScript 1.8.0
(function() {
  var repl, start_repl;

  repl = require("repl");

  start_repl = function(context) {
    var k, r, v, _results;
    r = repl.start("> ");
    _results = [];
    for (k in context) {
      v = context[k];
      _results.push(r.context[k] = v);
    }
    return _results;
  };

  module.exports.start_repl = start_repl;

}).call(this);
